version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - '.:/app'
      - '.bundle:/usr/local/bundle'
    working_dir: /app
    ports:
      - '3000:3000'
      - '8080:8080'
    command: bundle exec rackup -o 0.0.0.0 -p 3000
