FROM evserykh/rails:ruby2.6

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

RUN apt-get update && \
    apt-get install -y --no-install-recommends enca \
                                               libfile-mimeinfo-perl \
                                               libreoffice \
                                               libreoffice-l10n-ru \
                                               locales \
                                               locales-all \
                                               openjdk-11-jre-headless \
                                               uchardet \
                                               unzip

ENV LANG ru_RU.UTF-8
ENV LANGUAGE ru_RU:ru
ENV LC_ALL ru_RU.UTF-8

RUN set -eux; \
	apt-get update; \
	apt-get install -y gosu; \
# verify that the binary works
	gosu nobody true

COPY jodconverter-tomcat.tar.gz /opt
RUN cd /opt && \
    tar -xf jodconverter-tomcat.tar.gz && \
    rm jodconverter-tomcat.tar.gz

RUN useradd -m -s /bin/bash ruby && mkdir /converter

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]
